config/routes.rb
Rails.application.routes.draw do
  get '/artists', to: 'artists#index'
  get '/artists/:id', to:'artists#show', as: 'artist'
  get '/artists/new', to:'artists#new'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  require 'rspotify'
  RSpotify.authenticate(ENV["SPOTIFY_KEY"], ENV["SPOTIFY_SECRET"])
  Yt.configure do |config|
    config.api_key = ENV["YOUTUBE_KEY"]
  end
  # token = lastfm.auth.get_token
  # lastfm.session = lastfm.auth.get_session(token: token)['key']


  def index
    if !params[:artist_name].empty?
        lastfm = Lastfm.new(ENV["LASTFM_KEY"], ENV["LASTFM_SECRET"])
        @videos = Yt::Collections::Videos.new
        artistspotify = RSpotify::Artist.search(params[:artist_name])
        @artistlastfm = lastfm.artist.get_info(artist: params[:artist_name], autocorrect: 1)
        
        @artistbio = @artistlastfm["bio"]["content"]
        
        puts artistspotify
        @artist = artistspotify.first
        @tracks = @artist.top_tracks(:US)

        @tracks[0..4].each_with_index do |track, i|
          @videoId = @videos.where(q: "music video for #{@artist.name} #{track.name}", order: 'relevance').first.id
          @videoUrl = "<iframe src='//www.youtube.com/embed/#{@videoId}?autoplay=1' frameborder='0' allowfullscreen></iframe>"
      end
        
        # <% @videoId = @videos.where(q: "music video for #{@artist.name} #{track.name}", order: 'relevance').first.id %>
        # @videoId = @videos.where(q: params[:artist_name], safe_search: 'none').first.id
    else
        redirect_to root_path
    end  
  end
  def new
    respond_to do |format|
      format.js {render layout: false} # Add this line to you respond_to block
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/artists/_show.html.erb
<% render partial: 'show', :locals => {:videoId => @videoId } %>

app/views/artists/_video.html.erb
<div class="m-auto border border-dark w-100"><h4>VIDEOS</h4>
        
        <div id="video#{i + 1}">
          <%= sanitize @videoUrl%>
        <div>
        
      </div>

app/views/artists/index.html.erb
<br><br><br><br><br>
<%# ---- FULL CONTAINER FOR ALL ---- %>
<div class="justify-content-center align-items-center w-75 h-100 h-75 bg-transparent m-auto">
  <%# ---- PART ONE ::: ARTIST BIO ---- %>
  <div class="intro col-lg-6 p-2 mb-2 rounded">
    <h2><%= @artist.name %></h2>  
      <h6>Artist Bio( from last.fm api)</h6>
      <p><%= truncate( @artistbio, escape: false, length: 450) %></p>
      <p><%=link_to "Read more...", @artistlastfm["url"] , target: "_blank", rel: "nofollow" %></p>
  </div>


  <%# ---- PART 2 :: MUSIC PLAYER COMPONENT ---- %>
  <div class="player d-flex align-items-start col-lg-12 p-0 mt-2 rounded">
    <%# ---- 2AAA TRACK PLAYLIST ---- %>
    <div class="tracklist row col-lg-4 p-1">
      <div class="m-auto border border-dark"><h4>Top Tracks</h4>
        <button class="btn">Play</button>
        <table class="table table-hover table-striped custab rounded">
          <% @tracks[0..4].each_with_index do |track, i| %>
            <tr>
              <td class="p-1"><%= i + 1%></td>
              <td><%= link_to truncate( track.name, length: 30), :action => :new, remote: true, id: "ajaxcall" %></td>

            </tr>
          <% end %>
        </table>
      </div>
    </div>
    <%# ---- 2BBB EMBED VIDEO HERE ---- %>
    <div class="videoplayer row col-lg-8 p-1 border border-dark">
        <div id="videodiv">
        <%= render partial: "artists/video" %>
        </div>
    </div>
    </div>

    <%# ---- comments ---- %>
    <%# ---- comments ---- %>



  </div><%# ---- <---CLOSES PAGE CONTAINER ---- %>
    

app/views/artists/new.js.erb
$("videodiv").html("<%= escape_javascript(render partial: 'artists/new', locals: { videourl: @videoUrl }) %>");

app/views/artists/show.html.erb
<h1 class="page-header"><%= @artist.name %></h1>  
  <ul>
    <% @tracks(country: 'US').each(0..4) do |track| %>
      <li>
        <%= track.name %>
      </li>
    <% end %>
  </ul>

app/views/artists/show.js.erb
<iframe src="//www.youtube.com/embed/<%=@videoId%>?autoplay=1" frameborder="0" allowfullscreen></iframe>

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->

<br><br><br><br><br><br> <br><br>

<div class="form-inline d-flex justify-content-center align-items-center h-100" style="height: 100%;">
    <%= form_tag artists_path, method: "get", html: { class: "form-group" } do %>

      <div class="form-group mb-2">
        <%= text_field_tag(:artist_name, "", placeholder: "Enter artist name", class: "form-group row rounded m-2") %>
        <%= submit_tag "Search", class: 'btn-secondary btn-sm' %>
      </div>

    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpotifyDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Cormorant:400,700|Open+Sans:400,600" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container col-lg-12">
      <%= yield %>
      </div>
  </body>
</html>